_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.fire_net.FireNet
  input_channels: 5
  hidden_channels: 16
  kernel_size: 3
  head: 
    _target_: src.models.components.subcomponents.ClassificationHead
    input_channels: 16
    input_shape: [34, 34]
    num_classes: 10

# compile model for faster training with pytorch 2.0
compile: false